// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6l3vFLNNwnXqasRojujDuSBSRCMFQPI',
    appId: '1:922665310078:web:bcaff520b8fdb30eb8c52f',
    messagingSenderId: '922665310078',
    projectId: 'travelmission-2025-998b8',
    authDomain: 'travelmission-2025-998b8.firebaseapp.com',
    storageBucket: 'travelmission-2025-998b8.firebasestorage.app',
    measurementId: 'G-CQKF1CJ4Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3nGeDvrwRw1QPJPLx0Oslr-3apizJ9E',
    appId: '1:922665310078:android:e7da8cf9721ec6d1b8c52f',
    messagingSenderId: '922665310078',
    projectId: 'travelmission-2025-998b8',
    storageBucket: 'travelmission-2025-998b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUODFnrUJAeUgHwxNiWLbcJY-KYmSHCo',
    appId: '1:922665310078:ios:ec79bc0f1e353c9bb8c52f',
    messagingSenderId: '922665310078',
    projectId: 'travelmission-2025-998b8',
    storageBucket: 'travelmission-2025-998b8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKUODFnrUJAeUgHwxNiWLbcJY-KYmSHCo',
    appId: '1:922665310078:ios:ec79bc0f1e353c9bb8c52f',
    messagingSenderId: '922665310078',
    projectId: 'travelmission-2025-998b8',
    storageBucket: 'travelmission-2025-998b8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo6l3vFLNNwnXqasRojujDuSBSRCMFQPI',
    appId: '1:922665310078:web:7eaf5cc74272ad08b8c52f',
    messagingSenderId: '922665310078',
    projectId: 'travelmission-2025-998b8',
    authDomain: 'travelmission-2025-998b8.firebaseapp.com',
    storageBucket: 'travelmission-2025-998b8.firebasestorage.app',
    measurementId: 'G-WYLBV6R1JL',
  );
}
